# Numpy Module Introduction using [Link](https://github.com/jrjohansson/scientific-python-lectures/blob/master/Lecture-2-Numpy.ipynb)

# Introduction to numpy -
Numpy is a python module used in all numerical computations.
> Why use numpy instead of lists? 
> * numpy is faster, convenient and consumes less memory than python lists. Also numpy gives powerful vector and matrix and higher-dimensional data structures in python.
* Written in C and Fortran.

In [3]:
from numpy import * # numpy module imported.

### Creating numpy arrays-
We can initialize new numpy arrays using
* Python Lists/ Tuples.
* Using array generating functions such as arange etc.
* Reading from files.

### 1. Using Lists -

In [9]:
vector = array([1,2,3,4,5]) # Argument to the array function is a Python List
matrix = array([[1,2],[3,4]]) # Argument is a nested Python list
vector, matrix

(array([1, 2, 3, 4, 5]), array([[1, 2],
        [3, 4]]))

The vector and matrix are both objects of type **ndarray** provided by numpy module.

In [10]:
type(vector),type(matrix)

(numpy.ndarray, numpy.ndarray)

* The difference between them is only in their shapes. (Use ndarray.shape())
* The number of elements in the array is given by the ndarray.size.
* type of Data is given by ndarray.dtype.
* Numpy arrays are statically typed and homogenous. The type of ements in the array is determined before creating it.
* We can explicitly define the type of the array data when created using arguments. Some common dtypes are complex, float, int bool etc.

In [23]:
print("Vector Shape -> {}".format(vector.shape))
print("Matrix Shape -> {}".format(matrix.shape))
print("Vector Size -> {}".format(vector.size))
print("Matrix Size -> {}".format(matrix.size))
print("Vector Dtype -> {}".format(vector.dtype))
print("Matrix Dtype -> {}".format(matrix.dtype))
matrix = array([1,2,3,4,5,6], dtype=complex)
matrix

Vector Shape -> (5,)
Matrix Shape -> (6,)
Vector Size -> 5
Matrix Size -> 6
Vector Dtype -> int64
Matrix Dtype -> complex128


array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

### 2. Using Generating functions -

For large arrays it is impractical to do it manually. Instead we can use one of the many generating functions in numpy module of different forms.

In [30]:
# arange -
x = arange(0,10,3) # start,stop,step
print(x)
y = arange(-1,1,0.1)
print(y)

[0 3 6 9]
[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]


In [ ]:
# linespace & logspace